[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [
  { access = "read-write", path = "./"},
]
evm_version = "Cancun"
# optimizer is enabled by default, can produce different bytecode and mess with contract verification
# optimizer = false

# Note: If DeployScripts tests run into OutofGas errors, could be a memory issue:
# https://github.com/foundry-rs/foundry/issues/3971
# memory_limit = 335544320

remappings = [
  "@chainlink/ccip/=lib/ccip/contracts/src/v0.8/ccip/",
  "@chainlink/ccip-vendor/=lib/ccip/contracts/src/v0.8/vendor/",
  "forge-std/=lib/forge-std/src/",
  "@6551/=lib/reference/src/",
  "@eigenlayer-contracts/=lib/eigenlayer-contracts/src/contracts/",
  "@openzeppelin-v5/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
  "@openzeppelin-v5/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  # Note: Eigenlayer uses OpenZeppelin v4
  "@openzeppelin/contracts/=lib/eigenlayer-contracts/lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/eigenlayer-contracts/lib/openzeppelin-contracts-upgradeable/contracts/"
]

[rpc_endpoints]
localhost = "http://localhost:8545"
holesky = "https://holesky.drpc.org"
# Note: Free RPCs may sometimes fail
ethsepolia = "https://sepolia.drpc.org"
basesepolia = "https://sepolia.base.org"

[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}" }
ethsepolia = { key = "${ETHERSCAN_API_KEY}" }
basesepolia = { key = "${BASESCAN_API_KEY}" }
